language: java

cache:
  directories:
    - $HOME/.m2

install:
  - java -XX:+PrintFlagsFinal -version
  - mvn --version

script: mvn clean verify

jdk: oraclejdk8

notifications:
  email:
    - haystack-notifications@expedia.com
